### ISSUE TITLE
Memory issue for converting the model?

### ISSUE THREAD

**Issue by ajana1989** [lopuhin/python-adagram#14] opened 2018-09-06 11:46 UTC
As I increase the value of Alpha, the number of senses per word increases and as a result the model size is also increasing. My corpus size is 45 gb, with alpha=0.1 model size is 22G, with alpha=0.15, model size is 25G. Following the instructions, I tried to convert the julia model to json and then to python format, but it is giving memory error in the process of converting json to python format. The vm.json files are of size  89 gb and 96 gb respectively. So the memory requirement is increasing almost exponentially. Is there any way out to avoid this situation ?

**Comment by lopuhin** [comment] 2018-09-06 11:50
@ajana1989 unfortunately there is no solution for this at the moment. The way to fix this would be to either switch to a more memory efficient format (see https://github.com/lopuhin/python-adagram/issues/11#issuecomment-316159811), or use iterative json readers/writers, or make a direct convertor from julia format.
Closing this as a duplicate of #11 (this one will be linked there, thanks for reporting it!)

**Closed as completed by lopuhin** 2018-09-06 11:50 UTC
